<?php
	
	$collection=$this->getCollection();
	$__helper = Mage::helper('avik_faq');
	
?>

<div class="twd_container">
  <h1 style=""><?php echo $__helper->getFaqTitle();?></h1>
  <!-- drop down menu -->
  <?php echo $this->getPagerHtml(); ?> 
  
  <!-- responsive accordian -->
  <?php foreach($collection AS $faq): ?>
  
  <div id="ID_<?php echo $faq->getData('faq_id');?>" class="expandContent">
    <h3 class="faq-header">
	  <div class="plus icon" id="plus"></div>
      <div class="headerColumn1"><?php echo $this->htmlEscape($faq->getData('faq_title'));?> </div>
      
      <div class="expandedContentClearFloat"></div>
    </h3>
    <div class="expandedContent">
	<?php echo $__helper->filter($faq->getData('faq_description')); ?>
	</div>
  </div>
  <div class="clearfloat"></div>
  <?php endforeach; ?>
 <?php echo $this->getPagerHtml(); ?>  
  
</div>

